---
version: "3.9"
services:
  backend:
    build: ./backend/.
    ports:
      - "8000:8000"
    volumes:
      - "./backend/:/app"
    networks:
      - backend

  frontend:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      # - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/nginx/site.conf:/etc/nginx/sites-enabled/site.conf
    networks:
      - backend


networks:
  backend:
    name: backend
